baseURL = 'https://www.abu.rocks/'
languageCode = 'en-us'
title = 'Abu'
contentDir = 'content'
enableEmoji = true

[module]
  [[module.imports]]
    path = "github.com/colinwilson/lotusdocs"
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser.attribute]
    block = true

[params.docs]
darkMode = true

[permalinks]
  [permalinks.page]
    docs = "/docs/:sections[1:]/:slug/"
  [permalinks.section]
    docs = "/docs/:sections[1:]/"

[params.landing]
enable = false
